### ISSUE TITLE
Stopped working

### ISSUE THREAD

**Issue by adefaria** [foudfou/FireTray#160]
I'm on Ubuntu 14.04 with TB 31.3.0. FT is 0.5.4. Stopped working. Now does nothing. When I minimize or close TB TB just goes away. FT does nothing. HELP!

Please email me at adefaria@gmail.com as I probably will never come back here to check to see if this is updated.

**Comment by foudfou** [comment]
Andrew, what reaction do you expect from me, by posting twice [a very bad review on AMO](https://addons.mozilla.org/fr/firefox/addon/firetray/reviews/665336/) ? Do you think I'll take it as an encouragement for keeping working, *especially* on your problem ?

**Comment by adefaria** [comment]
Yes that's exactly what I would expect and exactly what I would do if I 
were the developer. Why do you ask? It seems to me obvious.

On 01/15/2015 09:15 AM, foudfou wrote:
>
> Andrew, what reaction do you expect from me, by posting twice a very 
> bad review on AMO 
> <https://addons.mozilla.org/fr/firefox/addon/firetray/reviews/665336/> 
> ? Do you think I'll take it as an encouragement for keeping working, 
> /especially/ on your problem ?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/foudfou/FireTray/issues/160#issuecomment-70122055>.
>


-- 
Andrew DeFaria
<http://defaria.com>
If a turtle doesn't have a shell, is he homeless or naked?

**Comment by foudfou** [comment]
Oh I see. Motivation with a stick...
I *think* this is not working. I'm sure it's not working for me.

We both agree on wanting to make a good job. The essential part is when somebody wants to share a critic, how it is done, and why it is done so.
BTW this reminds me of the first pages of the Hagakure, but I can't find any link to it. Basically it says that critics should be made in a cheerful way, when you are certain to have understood the views of the one you want to blame.
Giving the worst grade is not a constructive critic, it does not *bring* anything does it ?  "Not *why yesterday*, but *how tomorrow*" as they say.

For instance, I don't think I did a bad job with v0.5.4. In fact I brought FireTray to Unity and Plasma5 users (#130), while keeping it working for most Linux and all Windows users, and although I did not really want to do it. So cool down, read the issues, and downgrade to v0.5.3 while the issue is being solved.

It's not about being sensitive about my skills, which are certainly very limited, I grant you that. It's about your attitude toward me. Slapping someone in the face has never really motivated anyone. You'll see positive attitudes all around in this issue system: people trying to help find a solution.

I also see a contradiction in bad reviews as yours. You obviously appreciate the addon, or you have. But this does not appear in your reviews. And you obviously want to *continue* to use it, *urgently*.  So you probably value the addon. Why the worst grade then (twice) ?
I can somehow conceive that you are rating the usability of the addon: it's currently broken so it deserves the worst grade. If so I will expect you to give it the best grade regularly when it works. ...which [doesn't seem to happen much](https://addons.mozilla.org/fr/firefox/addon/firetray/reviews/user:4975892). In other words you only complain. Where's the carrot ?

While we are speaking of motivation, here is a [nice talk from Dan Pink](http://www.ted.com/talks/dan_pink_on_motivation?language=en) I'd like to share here.
Thank you for sharing your view, and giving me the opportunity to express my feelings.

**Comment by TiZ-EX1** [comment]
Go to about:config. Search for with_indicator, set it to false. Restart Thunderbird. This fixed it for me on XFCE.

**Comment by adefaria** [comment]
Thanks. That worked. Although it was with_appindicator, not with_indicator.

On 01/15/2015 11:04 AM, Trent McPheron wrote:
>
> Go to about:config. Search for with_indicator, set it to false. 
> Restart Thunderbird. This fixed it for me on XFCE.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/foudfou/FireTray/issues/160#issuecomment-70141583>.
>


-- 
Andrew DeFaria
<http://defaria.com>
Ever wonder what the speed of lightning would be if it didn't zigzag?

**Comment by TiZ-EX1** [comment]
Right, my bad.
