### ISSUE TITLE
Options window does not display complete

### ISSUE THREAD

**Issue by Mapaler** [foudfou/FireTray#180]
The options window is too long. I can't edit many options.
My screen size is 1366 x 768.
![Screenshot](http://ww3.sinaimg.cn/large/6c84b2d6jw1eshq9ttj36j211y0lcq6o.jpg)

The first install of Firetray I can see the top of options window(I'm not sure how to open it), but if I reload options window, it is change to previous pictures.
![Screenshot](http://ww4.sinaimg.cn/large/6c84b2d6jw1eshqib1iuxj211y0lcdl8.jpg)

**Comment by foudfou** [comment]
Hi,
The preferences window is indeed quite high.
I think this is OK with Thunderbird. I don't think splitting the *Mail* pane in multiple pane would make things clearer. On the contrary the pref window should be smaller for Firefox since the *Mail* pane is not displayed.
This has been [pointed here before](/foudfou/FireTray/issues/164#issuecomment-74774465) (#164).
Now, in general, if windows appear off-screen, you should be able to [move them without the title bar](http://superuser.com/questions/53585/how-to-move-windows-that-open-up-offscreen).
So I'll close this issue. Feel free to re-open it if I misunderstood.

**Comment by Mapaler** [comment]
I try to modify options.xul , use a whole "hbox" and two "vbox", change it to be fatter rather than slim and tall.
![my suggestion](http://ww2.sinaimg.cn/large/6c84b2d6jw1esipv5hx9zj211y0lcgrl.jpg)

**Comment by foudfou** [comment]
Alright. I'll do some testing when I get a chance.

**Comment by foudfou** [comment]
@Mapaler, would you care to submit a patch or a pull request ?

**Comment by Mapaler** [comment]
I don't know how to use GitHub.

![image 1](https://cloud.githubusercontent.com/assets/6565860/9428900/e14f308c-49f0-11e5-8ba3-414e8d0704d5.jpg)
![image 2](https://cloud.githubusercontent.com/assets/6565860/9428901/e1662378-49f0-11e5-9d3e-9735f0836312.jpg)
![image 3](https://cloud.githubusercontent.com/assets/6565860/9428902/e16a26a8-49f0-11e5-8421-8798183d2167.jpg)

Mean :
```xml
<horizontal box>
	<vertical box>
		Left Items
	</vertical box>
	<vertical box>
		Right Items
	</vertical box>
</horizontal box>
```

Code :
```xml
<hbox>
	<vbox>
		abc
	</vbox>
	<vbox>
		abc
	</vbox>
</hbox>
```
