### ISSUE TITLE
Borken in Firefox 46

### ISSUE THREAD

**Issue by Noitidart** [foudfou/FireTray#222]
Up till and including Firefox 45, it is ok to lib.delcare('gdk2') however in Fx46+ all functions return null. The simple fix is to lib.declare('gdk3').

This addon is superb, the only other good one out there was not updated since 2012 and is in shambles - https://addons.mozilla.org/en-US/firefox/addon/minimizetotray-revived/?src=github-firetray

**Comment by foudfou** [comment]
Hi Noida! The replacement has already occured. See [linux/gtk3/gdk.jsm](/foudfou/FireTray/blob/master/src/modules/ctypes/linux/gtk3/gdk.jsm).
Firetray broken in FF46 because [the logging module is broken](/foudfou/FireTray/blob/master/src/modules/logging.jsm#L98).
If you happen to fix it, I'll be happy to push an update to AMO.

**Comment by Noitidart** [comment]
Hey Foufou! :) 
Ooo thanks for that. You are way ahead of me on the game :)

Do you know why it was returning null? I couldn't figure it out till just now, I had this issue with my addon and finally realized it haha.

I'll try to help out I really love this addon :)

**Comment by Noitidart** [comment]
Hey @foudfou in GDK3 we can't use `gdk_x11_drawable_get_xid` anymore as that's a GDK2 function. Importing it in Firefox > 45 imports fine but it returns 0, as do all GDK2 functions in Fx>45 as they are incompatible.

Is there anyway we can do `gdk_x11_drawable_get_xid` functionality in GDK3?

**Comment by b3nmore** [comment]
Changing
```javascript
messageString = [ ("" + mo) for each ([,mo] in Iterator(message.messageObjects)) ].join(" ");
```
in [logging.jsm](https://github.com/foudfou/FireTray/blob/master/src/modules/logging.jsm#L98) to
```javascript
messageString = [for (mo of Iterator(message.messageObjects)) ("" + mo)].join(" ");
```
makes firetray working again in ff46.

However, I'm not entirely sure, if this reproduce the former behavior (because I don't understand it). Anyway, I would give it a try. So if you @foudfou could push an update to AMO, it would be highly appreciated.

**Comment by foudfou** [comment]
Just pushed v0.6.1 to AMO. I haven't tested it and hope it passes review.
@b3nmore, you can still build it yourself. See wiki for instructions.

**Comment by b3nmore** [comment]
Thanks for pushing.

> @b3nmore, you can still build it yourself. See wiki for instructions. 

Yeah, thats what I'm doing to test things. However AMO is just more comfortable to distribute it to several machines ;) .
