### ISSUE TITLE
Thunderbird 57+ support

### ISSUE THREAD

**Issue by salaros** [foudfou/FireTray#238]
This message is for contributors (people who fork this repo): please implement mozilla57+ migrations in order to make this addon compatible with TB 57+

**Comment by UksusoFF** [comment]
@salaros https://foudil.fr/blog/209/the-web-is-not-the-platform/

**Comment by yannours** [comment]
@salaros You can still use the actual firetray for thunderbird 50+ by force download the addon & install it manually in the option, I did it for 52.6.0 (64-bit) and it works properly.

**Comment by salaros** [comment]
@yannours  yeah, it worked on versions <= 52, but as you can see I opened this ticker for versions >= 57
If you don't believe me, just try upgrading to Thunderbird 57/58 👍

**Comment by yannours** [comment]
@salaros Ofc I believe you :) My bad wasn't wondering a 57+ disrupting, no way for me to upgrade so :D

**Comment by salaros** [comment]
@yannours some massive API changes took place in 52 -> 57/58 transition, with many breaking changes
That's  why I wanted some to take a look at it, before I got with a rewrite (probably I will have to, right after TB 57/58 goes stable)

**Comment by ghost** [comment]
Is someone planning to fork this project?

**Comment by salaros** [comment]
@jonlandrum I'm planning to do it if I fail to find a new maintainer for TB 57+ version here, I already maintain tons of open-source projects (some of them are mine, some were adopted), that's why I'm hesitating and trying to find some help before attempting a rewrite by myself

**Comment by kelvinau** [comment]
It will be great for 60+ version too :)

**Comment by s-m-e** [comment]
In case anyone is considering a fork or devoting some time into making just any tray add-on for Thunderbird 60+ work again, I am hereby cross-referencing [MinTrayR issue 238](https://github.com/nmaier/mintrayr/issues/188).

**Comment by CubicF** [comment]
I forked FireTray yesterday (because it seems to be the only minimize-to-tray extension that shows the number of currently unread messages) to see how far I can get (I had no experience with JS yet).

I did some minor updates according to the [Thunderbird/Add-ons Guide 57](https://wiki.mozilla.org/Thunderbird/Add-ons_Guide_57) but ran into the problem that the .xpi file was not unpacked during installation (`addon.pack` in `XPIInstall.jsm` in line 1858 is not set). 

I managed to install the extension using a text file to reference the unpacked extension files as described [here](https://developer.mozilla.org/en-US/docs/Mozilla/Thunderbird/Thunderbird_extensions/Building_a_Thunderbird_extension_7:_Installation). But after the installation of the extension Thunderbird crashes within seconds after every application start. 

I was not able to figure out how to properly debug the extension on startup. So my next approach would be to turn the extension into a bootstrapped extension to make debugging easier. I already began the work in the bootstrap branch, but [step 6](https://developer.mozilla.org/en-US/docs/Archive/Add-ons/How_to_convert_an_overlay_extension_to_restartless) seems to be a bit more work that I won't have time for in the next few weeks.

**Comment by rodricels** [comment]
@CubicF FYI, I tried your fork (bootstrap and thunderbird_quantion branches), thanks!

I found:
- installation works (without restart in bootstrap branch)
- configuration window doesn't save
- on bootstrap branch, the "start minimized" doesn't work, maybe because the configuration windows doesn't have icon names (quantion branch have it and works fine)

Thunderbird 60, Ubuntu 18.04 with Cinnamon 3.8

**Comment by jamesrobb** [comment]
@CubicF I also tried your fork. It installed, but it didn't seem to do anything.

There didn't appear to be any configuration menu available from the add-ons menu, and I didn't see any icons in my system tray. I'm not sure what exactly the expected behaviour should be.

Thunderbird 60, Manjaro Linux 17.1.12 with Gnome 3.28.2

**Comment by CubicF** [comment]
@jamesrobb If you tried to install the .xpi file it was presumably not unpacked during installation (at least this was the case for me). Therefore some icons can not be found (as you can see in the error console, which can be found in the "Tools -> developer tools" menu).

As I already mentioned, I tried to circumvent that problem by install the extension via referencing the unpacked sources. But if I do this, Thunderbird crashes at start-up before I can open the error console to see what went wrong.

Despite converting to a boot-strapped extension for better debugging (which would need some time because I have virtually no knowledge of the subject) I'm pretty clueless.

**Comment by kolinger** [comment]
Support for unpacked extension was removed (https://blog.mozilla.org/addons/2018/02/22/removing-support-unpacked-extensions/). This is why "unpack true" will not work anymore. I tried to load native libraries via ctypes from packed xpi file but this always fails (ctypes.open,  error 126/file not found).

https://developer.mozilla.org/en-US/docs/Mozilla/js-ctypes/Using_js-ctypes/ctypes.open 
This page is saying that ctypes.open() will load from xpi/jar but it doesn't work. I checked everything. Packed xpi file is okay, libraries are in there, in correct folder. Path is generated exactly as said in documentiation. But it fails. With "jar:" without "jar:". Any combination. Always fails with "not found" error.

Ugly hack can be implemented (like placing native libraries outside xpi, in some predefined path). This will break instalation process and extra steps will be needed. This solution will be unusable for less experienced users. Using unpacked extension in dev mode (via proxy file) is also ugly/not portable hack. 

Even if hacked then this may not work for long. Firefox did kill ctypes already (https://bugzilla.mozilla.org/show_bug.cgi?id=1444502). Also firefox will soon (or already did) drop support for "legacy" extensions. WebExtensions is the future. WebExtensions will not support ctypes either https://discourse.mozilla.org/t/ctypes-possible-in-webextensions/12490. Thunderbird slowly follows this path.

I don't see any way how to fix this issue properly. There is no long term solution.

----

This issues is hard to fix and fix may not work for long. Firefox/Thunderbird is killing powerful utilities for extensions (because of security). And tray extensions need these powerful utilities to work.

This should by implemented in firefox/thunderbird natively. Great solution for everyone. But it won't happen https://bugzilla.mozilla.org/show_bug.cgi?format=default&id=208923.

So Firefox/Thunderbird will not implement this but they remove support for extensions. Yea... We can't do much. This is about direction what Firefox and Thunderbird is heading...

I hope they will change their mind about native implementation. There is no other way.

Prove me wrong. Please.

**Comment by firetray-updates** [comment]
I continued what CubicF started and got FireTray up and running. The addon seems to work fine, but I barely used it and didn't try everything.

The changes I made are here: https://github.com/firetray-updates/FireTray/tree/thunderbird-57

**Comment by kilobyte** [comment]
@firetray-updates: your version does show an icon with new mail count, but closing the window kills Thunderbird, and minimizing it keeps it on the task bar.  (Debian, xfce)

**Comment by YamashitaRen** [comment]
@kilobyte Not having theses issues on Plasma5/SystemTray. Didn't try appindicator.
Using it without appindicator prevents you from getting the new mail count though...

**Comment by firetray-updates** [comment]
@kilobyte FireTray is disabling the chat plugin here because it's not supported, so I missed the `firetray.Messaging.Accounts()` there. I updated the code (force-pushed), try it now.

**Comment by kilobyte** [comment]
@firetray-updates: yay it works!

**Comment by jamesrobb** [comment]
@firetray-updates Can confirm! I don't seem to have a way to configure it yet, but the tray icon is indeed back. Thanks!

**Comment by ZTHawk** [comment]
Tried it on windows 10. Minimizing TB will keep it in taskbar.
SysTray icon is visible but I cannot interact with that icon.

**Comment by Thrilleratplay** [comment]
@firetray-updates  Also can confirm with using XFCE.  Thank you for fixing this.  Mind publishing this as an official add on?

**Comment by firetray-updates** [comment]
@ZTHawk I'm sorry, I didn't try this on Windows. I suspect your problem is related to the unpacking issue that CubicF mentioned. I assume it's a Windows specific problem, because I didn't have to do anything special to install the addon.

@Thrilleratplay I'm not planning on supporting this ATM, I just fixed it because I like it and apparently it still needs some changes.

**Comment by leledumbo** [comment]
Nice! At least tray icon appears and close to tray works, clicking it also brings back the app which is all I need for this addon.

**Comment by AdmiralAsshat** [comment]
@firetray-updates, working well on Cinnamon. Thanks!

**Comment by ghost** [comment]
I wonder if Thunderbird contributors ever use Thunderbird themselves, since apparently this has been a feature request since 2003 and nobody in 15 years got uncomfortable enough to implement this core functionality in the application (I have never seen any other application that has "minimize to tray" functionality implemented as an addon, this is hilarious and absurd). Unfortunately, I am useless here, so, please, if you consider developing a new extension like FireTray, instead consider first implementing this in Thunderbird itself, be it AppIndicator, GtkTrayIcon -- basically, whatever at this point, since it will never be accepted upstream (ticket about this was marked as RESOLVED WONTFIX, also absurd), and we can just compile it ourselves.

**Comment by kilobyte** [comment]
@light2yellow: I for one use Thunderbird _because_ of this functionality, and will look for another mail client the moment it stops working (in Debian, TB52 is still in stable and testing, only unstable has 60).  The fix by @CubicF and @firetray-updates is great.  My use case for Thunderbird is twofold: 1. glorified biff, 2. something to read that HTML mail from a business critter; for anything else I use mutt.  No close-to-tray means the first — my main — use is out.  And I receive ~1000 text mails per day (LKML is spammy...) vs maybe 12 HTMLs I elect to even open per **year**.

The only reason for WONTFIX was that "operating systems deprecate system tray".  Except that Windows 10 recommendations explicitly list new mail notifications as **valid** use of the tray, and the only Linux environment that hypocritically deprecates tray despite using it itself is GNOME.

**Comment by ZTHawk** [comment]
@kilobyte If you found evidence that win10 recommends systray then you should post it on mozilla bug tracker to state the old reason as invalid.

**Comment by kilobyte** [comment]
" You are not allowed to make an additional comment on this bug. "

Here's Microsoft docs about [notifications](https://docs.microsoft.com/en-us/windows/desktop/uxguide/mess-notif) and [systray icons](https://docs.microsoft.com/en-us/windows/desktop/uxguide/winenv-notification).  It lists Outlook as an example of "Correct" purpose of tray icon, and provides a long list of conditions that are required for a permanent icon to be acceptable, Thunderbird matching them all.

As for Linux: GNOME is a lost cause, and I have nothing but pity for its users.  People who use any other environment can, and often want to, use systray.

**Comment by jamesrobb** [comment]
I think this is definitely something that should be brought up with the Thunderbird developers. I think its hasty to say that system trays are a thing of the past considering the majority of people today still use OSX and Windows, which to date still have system trays. For Linux, I don't think its fair to point out a single DE and use their ever evolving design paradigm as justification for not implementing a very common feature of a mail/messaging client.

**Comment by YamashitaRen** [comment]
I sure would have loved to make some passive-agressive comment about how "and on linux this isn't really a thing" is wrong.
The bug report has been closed for wrong reasons and another one should be reopened. Unfortunately I can't be bothered with spearheading a bug report toward such close-minded developers...

**Comment by kelvinau** [comment]
I have switched to Evolution (https://wiki.gnome.org/Apps/Evolution). It can show the number of unread messages in the tray icon. That's enough for me already.

**Comment by lisuml** [comment]
For anyone interested, I created Arch AUR package that builds @firetray-updates fork.

**Comment by ZTHawk** [comment]
I have created a new bug report here: https://bugzilla.mozilla.org/show_bug.cgi?id=1490368

**Comment by firetray-updates** [comment]
@ZTHawk I have a VM with Windows 10, so yesterday I tried the addon there to see what's going on.

For some reason FireTray is unable to load the images stored inside the xpi. This is the reason why it does nothing on Windows, the addon starts and immediately stops working. Removing bits of code here and there to skip the loading of the images made the addon work. However, everything works fine only for a bunch of seconds, then Thunderbird crashes. I should probably use a debugger to know what's going on, because right now I'm clueless.

**Comment by hajj3** [comment]
@firetray-updates  If you could make a compiled .xpi of this so that i can install it even if it is buggy i'd appreciate it.

**Comment by kilobyte** [comment]
@hajj3: I don't know how to build the xpi, but if you're on Debian (or a derivative like Ubuntu or Mint), here's a package: https://angband.pl/debian/pool/main/f/firetray/ — built after mindlessly applying the diffs.  It uses some mozilla-devscripts scheme that I didn't even look inside.  Works perfectly for me.

Still no word from the maintainers; if no one says a word I'll propose a NMU shortly.

**Comment by hajj3** [comment]
> 
> 
> @hajj3: I don't know how to build the xpi, but if you're on Debian (or a derivative like Ubuntu or Mint), here's a package: https://angband.pl/debian/pool/main/f/firetray/ — built after mindlessly applying the diffs. It uses some mozilla-devscripts scheme that I didn't even look inside. Works perfectly for me.
> 
> Still no word from the maintainers; if no one says a word I'll propose a NMU shortly.

I'm using Windows 10 unfortunately.

**Comment by ghost** [comment]
Here is the xpi from https://github.com/foudfou/FireTray/issues/238#issuecomment-419705792 (with debug symbols): [firetray-0.6.1.xpi.zip](https://github.com/foudfou/FireTray/files/2375010/firetray-0.6.1.xpi.zip)

To use, unzip it first (github didn't allow to upload .xpi directly).

**Comment by hajj3** [comment]
> 
> 
> Here is the xpi (with debug symbols): [firetray-0.6.1.xpi.zip](https://github.com/foudfou/FireTray/files/2375010/firetray-0.6.1.xpi.zip)
> 
> To use, unzip it first (github didn't allow to upload .xpi directly).

thanks, unfortunately it won't minimize to the tray or close to the tray, i tried changing the options. I tested using thunderbird 60.0 x64 on win 10 x64.

**Comment by firetray-updates** [comment]
@kilobyte `cd src && make` ;)

@hajj3 the addon dies as soon as it tries to populate the menu of the tray, which includes the images.

**Comment by ghost** [comment]
> thanks, unfortunately it won't minimize to the tray or close to the tray

It didn't work (i.e. installed and launched correctly, just nothing happens) for me in TB 60 either (Arch Linux, XFCE), although I didn't have much hope about it.

The state of desktop mail clients is quite pathetic. Geary and Evolution have numerous bugs and glitches, and don't implement the standard used in XFCE for tray icons, KMail has a tray icon, but it refused to send an email from Gmail account (which is, like, the essential thing). Something like N1 fork (whatever name it has) requires additional cloud account. Mutt[4e] will just take too much time to figure out. There is no middle ground.

**Comment by kilobyte** [comment]
Being broken in Arch+XFCE on TB60 sounds weird — I wouldn't expect Debian's XFCE to be meaningfully different, yet updated firetray (as the package I linked) works fine for me.

**Comment by ghost** [comment]
So, you said that, and I went digging a little bit further -- just thought it's <=57. Managed to get it working in my environment too. I noticed that while opening the application there was something happening in xfce4-panel's systray: the visual space was allocated for an icon and then instantly deallocated. I gdb'ed the panel and noticed that the icon was the same as the one used for 'notifications' widget.

Then I went to Add-ons -> FireTray and selected a custom icon:
![](https://imgur.com/zFHK2Y6l.png)

And that fixed it for me. Thanks.

**Comment by firetray-updates** [comment]
I tried the addons on Windows once more. The problem with the icons not loading is due to the fact that the addon is not unpacked, despite the unpack flag set in install.rdf. Apparently Windows needs an unpacked extension: [XPI_unpacking](https://developer.mozilla.org/en-US/docs/Extensions/Updating_extensions_for_Firefox_4#XPI_unpacking). If I manually extract the addon, everything starts working as expected.

The crash I'm experiencing is instead caused by an access violation related to something [attachWndProc()](https://github.com/foudfou/FireTray/blob/0dd01042ccf298f5dd507c5151923d605ab5319e/src/modules/winnt/FiretrayWindow.jsm#L119) does. If I replace this function with a stub, Thunderbird stops crashing. That function should be needed to handle multiple windows and indeed FireTray only handles the main window after the change, but at least it won't crash the application.

**Comment by firetray-updates** [comment]
There's something I forgot to mention. The addon is entirely written in JS, the bits of native code are not used. The Makefile simply packages the xpi taking only the files used while stripping all the `log.debug()` calls. This means you can just download the source code, rename the `src` directory to `{9533f794-00b4-4354-aa15-c2bbda6989f8}` and place it in `~/.thunderbird/PROFILE/extensions` (Linux) or `%APPDATA%\Roaming\Thunderbird\PROFILE\extensions` (Windows). You'll have all the `log.debug()` lines and some extra files, but that's not a big deal. You may have to restart Thunderbird a couple of times, once to let it find the extension and once more to let it load it.

If you want to test the addon on Windows, I suggest you to comment out [this](https://github.com/foudfou/FireTray/blob/0dd01042ccf298f5dd507c5151923d605ab5319e/src/modules/winnt/FiretrayWindow.jsm#L120-L141). Not ideal, but at least Thunderbird will not crash.

**Comment by bryanmc57** [comment]
@firetray-updates Would you be willing to take a minute or two to list the step by step for installing this?  Running debian 9 but am not quite sure how to use the api to get firetray back up and running after the latest thunderbird 60 update.  Thanks

**Comment by kilobyte** [comment]
For Debian, you can take it from the official archive: http://ftp.debian.org/debian/pool/main/f/firetray/xul-ext-firetray_0.6.1+dfsg-1.1_all.deb — for now unstable only, but I asked for inclusion in stable updates.

**Comment by firetray-updates** [comment]
@bryanmc57 
```bash
git clone https://github.com/firetray-updates/FireTray
cd FireTray/src
make build
ls ../build-*/*.xpi    # <-- your xpi, ready to be installed
```
(you can use a packed extension on Linux, so the xpi is fine)

As I also mentioned in my previous comment, you can just download the source code (even via [github](https://github.com/firetray-updates/FireTray/archive/thunderbird-57.zip)), take the `src/` directory, rename it to `{9533f794-00b4-4354-aa15-c2bbda6989f8}` and place it in `~/.thunderbird/PROFILE/extensions`. The default profile is something like `XXXX.default`, read `~/.thunderbird/profiles.ini` for the exact name.

**Comment by vayulove** [comment]
> For Debian, you can take it from the official archive: http://ftp.debian.org/debian/pool/main/f/firetray/xul-ext-firetray_0.6.1+dfsg-1.1_all.deb — for now unstable only, but I asked for inclusion in stable updates.

I had firetray working with Thunderbird 52.4 all along. I had xul-ext-firetray (0.6.1+dfsg-1) installed from debian packages.  I'm on sid.  I had Thunderbird held, unfortunately I didn't have firetray held.  Today I did a system upgrade and this new firetray came in and broke my working firetray.  I tried reinstalling the old version but it still doesn't work.  I'm severely bummed.  How do I get it working again, is there a check for versions somewhere I can override?

**Comment by vayulove** [comment]
So I've got my old firetray working with Thunderbird 52.4 by adding a config setting: extensions.checkCompatibility.52.4 set to false

My new question is what exactly is the new version of firetray in the sid repository? Does it work for Thunderbird 60? Does it work the same way as the old firetray? Will it use my existing settings?  With the compatibility check I just turned off do you think your new firetray will work for Thunderbird 52.4?

**Comment by kilobyte** [comment]
@vayulove: how come xul-ext-firetray 0.6.1+dfsg-1.1 got upgraded if you had thunderbird held?  Its deps are:
```
Depends: thunderbird (>= 1:57.0) | icedove (>= 1:57.0)
Breaks: icedove (<< 1:57.0), thunderbird (<< 1:57.0)
```
which should have prevented the upgrade.  The new version works with TB60 but not TB52 — at least for me (breakage on Windows doesn't matter for us).  I did not notice any regressions within my use cases.

I'm not the maintainer of firetray in Debian but it was me who prepared and uploaded the new version, if something is wrong I'd be very interested in knowing — esp. before my upload gets accepted as a stable update.

**Comment by jalalsfs** [comment]
> @firetray-updates Also can confirm with using XFCE. Thank you for fixing this. Mind publishing this as an official add on?

I have XFCE on Fedora, I git clone https://github.com/firetray-updates/FireTray.git, do I have to compile it?

**Comment by jalalsfs** [comment]
> @bryanmc57
> 
> ```shell
> git clone https://github.com/firetray-updates/FireTray
> cd FireTray/src
> make build
> ls ../build-*/*.xpi    # <-- your xpi, ready to be installed

Thank you so much, it works with me on Fedora 28/XFCE

**Comment by sallyhaj** [comment]
@firetray-updates, I did what you've mentioned
```
git clone https://github.com/firetray-updates/FireTray
cd FireTray/src
make build
ls ../build-*/*.xpi    # <-- your xpi, ready to be installed
```
I am using Fedora 28/XFCE and it works, thank you so much,
There are more bugs reports on https://bugzilla.mozilla.org about tray icon.
Many guys there and on #thunderbird channel on IRC want some programmers to work on tray icon as a native option in TB settings, so if all the programmers who works on tray system plugins put their efforts on making it within TB, I think it would be much much better.
What do you think @firetray-updates ?

**Comment by tumbl3w33d** [comment]
> For Debian, you can take it from the official archive: http://ftp.debian.org/debian/pool/main/f/firetray/xul-ext-firetray_0.6.1+dfsg-1.1_all.deb — for now unstable only, but I asked for inclusion in stable updates.

Works great in stable with thunderbird 60.0-3~deb9u1 - thank you for the hint!

**Comment by firetray-updates** [comment]
@jalalsfs I simply fixed an existing extension following [these hints](https://wiki.mozilla.org/Thunderbird/Add-ons_Guide_57), I didn't write it from scratch. I put close to no effort into this, implementing this natively is a completely different matter and not something I feel like doing now. FireTray does the job for now, but I definitely wouldn't mind a native implementation.

**Comment by ghost** [comment]
> For Debian, you can take it from the official archive: http://ftp.debian.org/debian/pool/main/f/firetray/xul-ext-firetray_0.6.1+dfsg-1.1_all.deb — for now unstable only, but I asked for inclusion in stable updates.

Hi. This is good news to have firetray in Debian repositories.

Strangely, I can't get it working. Firetray appears as not compatible in Thunderbird extensions page. If someone can help. Thanks.

**Comment by kilobyte** [comment]
@zorzibaffo: can you check the version of your installed firetray and thunderbird?  The new version is compatible only with TB60 (package dependencies _should_ ensure that, but per a comment above, there might be something wrong).

Also, please check if you have a locally installed (ie, in Thunderbird's profile) copy?  This one may override the system-installed package.

**Comment by ghost** [comment]
> @zorzibaffo: can you check the version of your installed firetray and thunderbird? The new version is compatible only with TB60 (package dependencies _should_ ensure that, but per a comment above, there might be something wrong).
> 
> Also, please check if you have a locally installed (ie, in Thunderbird's profile) copy? This one may override the system-installed package.

Hello, and thanks for answering. I installed Thunderbird 60 from Debian repos, and Firetray 0.6.1 from Debian repos, too. Where should I check for locally installed copy ?

Edit: I'm sure I had removed previously manually installed firetray 0.6.1

**Comment by kilobyte** [comment]
0.6.1+dfsg-1 or 0.6.1+dfsg-1.1?  The former is for TB52 (and lower) only, the latter for TB60.

A localled installed copy can be removed via the "addons" page, a system-wide only disabled.

**Comment by ghost** [comment]
> 0.6.1+dfsg-1 or 0.6.1+dfsg-1.1? The former is for TB52 (and lower) only, the latter for TB60.
> 
> A localled installed copy can be removed via the "addons" page, a system-wide only disabled.

You're right. I installed 0.6.1+dfsg-1. It could not work. Maybe we can hope 0.6.1+dfsg-1.1 to be pushed in stable repos soon.
Thanks.

**Comment by OmegaPhil** [comment]
Devuan Ascii user here with Thunderbird 1:60.0-3~deb9u1 and xul-ext-firetray 0.6.1+dfsg-1.1 installed. Just reporting successful workingness of the 'display new message count' functionality now - the startup after the initial install was lacking icons so no systray appearance (even the Preferences page icon was missing), but disabling restarting and reenabling the addon worked. Thanks for your work kilobyte and firetray-updates.

**Comment by ghost** [comment]
Yes. it works perfectly. Thanks to firetray-updates and kilobyte.

**Comment by sunandmoonandus** [comment]
I also can confirm it works perfectly. There was also the " the startup after the initial install was lacking icons so no systray appearance (even the Preferences page icon was missing), but disabling restarting and reenabling the addon worked. " like OmegaPhil noted it. Disabling restarting and reenabling the addon worked.Thanks so much for your work firetray-updates and kilobyte!
Thunderbird 1:60.0-3~deb9u1 and xul-ext-firetray 0.6.1+dfsg-1.1 , Debian Stretch 9.5, 64Bit

**Comment by Chealer** [comment]
Thank you @kilobyte, I confirm Debian unstable's 0.6.1+dfsg-1.1 works on Debian 9 (with KDE) just like FireTray used to work with Thunderbird 52 and can be installed without any new dependency ( # dpkg -i xul-ext-firetray_0.6.1+dfsg-1.1_all.deb ).

In the long term, I'd agree a solution should be submitted to distributors such as Debian, as Mozilla itself appears hopeless at solving this.

**Comment by YogSottot** [comment]
There is released a new standalone system tray new mail notification for Thunderbird.  
https://github.com/gyunaev/birdtray - it uses Thunderbird email search database directly, and does not require extensions. Thus it will work even when Thunderbird will drop ctypes support.

**Comment by vayulove** [comment]
> @vayulove: how come xul-ext-firetray 0.6.1+dfsg-1.1 got upgraded if you had thunderbird held? Its deps are:
> 
> ```
> Depends: thunderbird (>= 1:57.0) | icedove (>= 1:57.0)
> Breaks: icedove (<< 1:57.0), thunderbird (<< 1:57.0)
> ```

Because those aren't the dependencies of the firetray I have installed:
`Package: xul-ext-firetray
Version: 0.6.1+dfsg-1
Depends: iceweasel (>= 7.0) | firefox (>= 7.0) | firefox-esr (>= 7.0) | thunderbird (>= 7.0) | icedove (>= 7.0)
`

I also use a non standard Thunderbird. I use one from Plasmazilla on Launchpad.  They have it patched to use KDE dialogs.  I've been using their Firefox and Thunderbird on debian for years.  They're not up to Thunderbird 60 yet.  Keep up the good work on firetray, I'll use your version when Plasmazilla gets up to Thunderbird 60.  I can't imagine not having taskbar functionality for email and I really don't want kmail and don't see any other alternatives I like.

YogSottot just posted an interesting and hopeful solution.

**Comment by NoXPhasma** [comment]
> For Debian, you can take it from the official archive: http://ftp.debian.org/debian/pool/main/f/firetray/xul-ext-firetray_0.6.1+dfsg-1.1_all.deb — for now unstable only, but I asked for inclusion in stable updates.

Thank you very much, this works like a charm on Linux Mint 19!

**Comment by logix2** [comment]
If anyone here is looking for a Birdtray PPA, I created one for easy installation: [https://www.linuxuprising.com/2018/10/birdtray-thunderbird-tray-icon-with-new.html](https://www.linuxuprising.com/2018/10/birdtray-thunderbird-tray-icon-with-new.html)

**Comment by vlatkoB** [comment]
@YogSottot Thanks for the info. Firetray, although working, didn't show an icon in the tray, but `birdtray` works like a charm. Had to switch to `mork` parser, though.
I'm on Arch, Cinnamon, TB 60.2.1.

**Comment by bryanmc57** [comment]
Seems today's update to TB 60.2.1 in Debian stable has broken firetray again.

**Comment by ghost** [comment]
> Seems today's update to TB 60.2.1 in Debian stable has broken firetray again.

It works for me, even after update to TB 60.2.1-2.

**Comment by ghost** [comment]
> Seems today's update to TB 60.2.1 in Debian stable has broken firetray again.

Sorry, I made a thread mistake.

You may try this one:

https://github.com/foudfou/FireTray/issues/242#issuecomment-433317687

**Comment by bryanmc57** [comment]
Interesting.  I checked synaptic and todays update was to 1:60.2.1-2 and the add-ons section shows firetray as disabled.

**Comment by lbratch** [comment]
> Seems today's update to TB 60.2.1 in Debian stable has broken firetray again.

I had the same problem with TB 60.2.1 but solved it by updating FireTray from Git.  I was using de3145c233bb0d57ccbe268bf5d685e4523645d5:

```
commit de3145c233bb0d57ccbe268bf5d685e4523645d5
Author: Gabriele <firetray-updates@users.noreply.github.com>
Date:   Sun Sep 9 20:09:28 2018 +0200

    Do not rely on StopIteration for the fade animation

    We now use a standard generator, which never throws StopIteration.
```
And updating to acbfa295d9d90d1a6e5f3472e4e02cb5f3441dad fixed it:
```
commit acbfa295d9d90d1a6e5f3472e4e02cb5f3441dad (HEAD -> thunderbird-57, origin/thunderbird-57, origin/HEAD)
Author: Gabriele <firetray-updates@users.noreply.github.com>
Date:   Sat Oct 13 12:07:57 2018 +0200

    Make it compatible with 60.*
```

(This is on the thunderbird-57 branch of https://github.com/firetray-updates/FireTray/commits/thunderbird-57)

**Comment by bryanmc57** [comment]
I'll give it a try, once I figure out how to do the update.  Help?

**Comment by Chealer** [comment]
> Seems today's update to TB 60.2.1 in Debian stable has broken firetray again.

I confirm. The extension is disabled again.

**Comment by ghost** [comment]
Solution here:

https://github.com/foudfou/FireTray/issues/242#issue-369079239

**Comment by Chealer** [comment]
Actually, it was already broken. I had fixed my Firetray by upgrading it to unstable's version, but that won't work this time for now (there is no newer Firetray version to fix again).

The issue is reported in [ticket #910973](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=910973).

**Comment by ghost** [comment]
You have to remove firetray if you installed it from debian repos, or via a deb.file.

Just download it from the following link, and install it from Thunderbird extensions page with "install from a file"

https://github.com/foudfou/FireTray/issues/242#issue-369079239

**Comment by ZTHawk** [comment]
> 
> 
> Solution here:
> 
> [#242 (comment)](https://github.com/foudfou/FireTray/issues/242#issue-369079239)

I can confirm that the version by @Ximi1970 (https://github.com/Ximi1970/FireTray/releases/tag/v0.6.1) is working very good with Win 10 x64 (to tray on minimize or on close).
Works with TB 60 and 60.2.1.

**Comment by kilobyte** [comment]
The Debian maintainer is not responding; I've put a NMU into DELAYED/2 — if no one does anything, the fix will be available in unstable in two days.

**Comment by Chealer** [comment]
Thanks to kilobyte, Debian unstable now contains xul-ext-firetray 0.6.1+dfsg-1.2: https://packages.debian.org/sid/all/xul-ext-firetray/download
This package can be installed on Debian 9 without bringing in any new dependency, and solves this. It may be necessary to restart Thunderbird twice though.

**Comment by jamesrobb** [comment]
I seem to be running into an issue with KDE (latest as of writing this). Everything works as expected except the icon is very blury in the system tray. I've read things here and there about this having something to do with AppIndicators, though I can't reason why an SVG icon would become blurry because this add-on doesn't expose an AppIndicator (my guess is that the icon is GtkStatusIcon).

Any idea on how to tackle this?

**Comment by firetray-updates** [comment]
@jamesrobb you need Appindicator if you want a high res icon. I mentioned that here not long ago: https://github.com/firetray-updates/FireTray/pull/3

**Comment by bryanmc57** [comment]
Version 68.2.2 has broken firetray again in Debian

**Comment by vayulove** [comment]
I gave up on firetray. Birdtray has been working great. I think I got it somewhere from a link on this thread. Now I'm using Thunderbird 70b straight from Mozilla, you can have it with KDE dialogs.
